//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace SW.WSRetention {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="wcfTimbradoRetencionesEndpoint", Namespace="http://tempuri.org/")]
    public partial class wcfTimbradoRetencionesEndpoint : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback TimbrarRetencionXMLOperationCompleted;
        
        private System.Threading.SendOrPostCallback TimbrarRetencionXMLV2OperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public wcfTimbradoRetencionesEndpoint() {
            this.Url = global::SW.Properties.Settings.Default.SW_sdk_45_WSRetention_wcfTimbradoRetenciones;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event TimbrarRetencionXMLCompletedEventHandler TimbrarRetencionXMLCompleted;
        
        /// <remarks/>
        public event TimbrarRetencionXMLV2CompletedEventHandler TimbrarRetencionXMLV2Completed;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IwcfTimbradoRetenciones/TimbrarRetencionXML", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string TimbrarRetencionXML([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string xmlRetencion, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string tokenAutenticacion) {
            object[] results = this.Invoke("TimbrarRetencionXML", new object[] {
                        xmlRetencion,
                        tokenAutenticacion});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void TimbrarRetencionXMLAsync(string xmlRetencion, string tokenAutenticacion) {
            this.TimbrarRetencionXMLAsync(xmlRetencion, tokenAutenticacion, null);
        }
        
        /// <remarks/>
        public void TimbrarRetencionXMLAsync(string xmlRetencion, string tokenAutenticacion, object userState) {
            if ((this.TimbrarRetencionXMLOperationCompleted == null)) {
                this.TimbrarRetencionXMLOperationCompleted = new System.Threading.SendOrPostCallback(this.OnTimbrarRetencionXMLOperationCompleted);
            }
            this.InvokeAsync("TimbrarRetencionXML", new object[] {
                        xmlRetencion,
                        tokenAutenticacion}, this.TimbrarRetencionXMLOperationCompleted, userState);
        }
        
        private void OnTimbrarRetencionXMLOperationCompleted(object arg) {
            if ((this.TimbrarRetencionXMLCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.TimbrarRetencionXMLCompleted(this, new TimbrarRetencionXMLCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IwcfTimbradoRetenciones/TimbrarRetencionXMLV2", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string TimbrarRetencionXMLV2([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string xmlRetencion, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string tokenAutenticacion) {
            object[] results = this.Invoke("TimbrarRetencionXMLV2", new object[] {
                        xmlRetencion,
                        tokenAutenticacion});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void TimbrarRetencionXMLV2Async(string xmlRetencion, string tokenAutenticacion) {
            this.TimbrarRetencionXMLV2Async(xmlRetencion, tokenAutenticacion, null);
        }
        
        /// <remarks/>
        public void TimbrarRetencionXMLV2Async(string xmlRetencion, string tokenAutenticacion, object userState) {
            if ((this.TimbrarRetencionXMLV2OperationCompleted == null)) {
                this.TimbrarRetencionXMLV2OperationCompleted = new System.Threading.SendOrPostCallback(this.OnTimbrarRetencionXMLV2OperationCompleted);
            }
            this.InvokeAsync("TimbrarRetencionXMLV2", new object[] {
                        xmlRetencion,
                        tokenAutenticacion}, this.TimbrarRetencionXMLV2OperationCompleted, userState);
        }
        
        private void OnTimbrarRetencionXMLV2OperationCompleted(object arg) {
            if ((this.TimbrarRetencionXMLV2Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.TimbrarRetencionXMLV2Completed(this, new TimbrarRetencionXMLV2CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    // CODEGEN: The optional WSDL extension element 'PolicyReference' from namespace 'http://schemas.xmlsoap.org/ws/2004/09/policy' was not handled.
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="wcfTimbradoRetencionesEndpoint1", Namespace="http://tempuri.org/")]
    public partial class wcfTimbradoRetencionesEndpoint1 : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback TimbrarRetencionXMLOperationCompleted;
        
        private System.Threading.SendOrPostCallback TimbrarRetencionXMLV2OperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;

        /// <remarks/>
        public wcfTimbradoRetencionesEndpoint1(string url) {
            this.Url = url+"/Timbrado/wcfTimbradoRetenciones.svc";
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event TimbrarRetencionXMLCompletedEventHandler TimbrarRetencionXMLCompleted;
        
        /// <remarks/>
        public event TimbrarRetencionXMLV2CompletedEventHandler TimbrarRetencionXMLV2Completed;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IwcfTimbradoRetenciones/TimbrarRetencionXML", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string TimbrarRetencionXML([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string xmlRetencion, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string tokenAutenticacion) {
            object[] results = this.Invoke("TimbrarRetencionXML", new object[] {
                        xmlRetencion,
                        tokenAutenticacion});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void TimbrarRetencionXMLAsync(string xmlRetencion, string tokenAutenticacion) {
            this.TimbrarRetencionXMLAsync(xmlRetencion, tokenAutenticacion, null);
        }
        
        /// <remarks/>
        public void TimbrarRetencionXMLAsync(string xmlRetencion, string tokenAutenticacion, object userState) {
            if ((this.TimbrarRetencionXMLOperationCompleted == null)) {
                this.TimbrarRetencionXMLOperationCompleted = new System.Threading.SendOrPostCallback(this.OnTimbrarRetencionXMLOperationCompleted);
            }
            this.InvokeAsync("TimbrarRetencionXML", new object[] {
                        xmlRetencion,
                        tokenAutenticacion}, this.TimbrarRetencionXMLOperationCompleted, userState);
        }
        
        private void OnTimbrarRetencionXMLOperationCompleted(object arg) {
            if ((this.TimbrarRetencionXMLCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.TimbrarRetencionXMLCompleted(this, new TimbrarRetencionXMLCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IwcfTimbradoRetenciones/TimbrarRetencionXMLV2", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string TimbrarRetencionXMLV2([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string xmlRetencion, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string tokenAutenticacion) {
            object[] results = this.Invoke("TimbrarRetencionXMLV2", new object[] {
                        xmlRetencion,
                        tokenAutenticacion});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void TimbrarRetencionXMLV2Async(string xmlRetencion, string tokenAutenticacion) {
            this.TimbrarRetencionXMLV2Async(xmlRetencion, tokenAutenticacion, null);
        }
        
        /// <remarks/>
        public void TimbrarRetencionXMLV2Async(string xmlRetencion, string tokenAutenticacion, object userState) {
            if ((this.TimbrarRetencionXMLV2OperationCompleted == null)) {
                this.TimbrarRetencionXMLV2OperationCompleted = new System.Threading.SendOrPostCallback(this.OnTimbrarRetencionXMLV2OperationCompleted);
            }
            this.InvokeAsync("TimbrarRetencionXMLV2", new object[] {
                        xmlRetencion,
                        tokenAutenticacion}, this.TimbrarRetencionXMLV2OperationCompleted, userState);
        }
        
        private void OnTimbrarRetencionXMLV2OperationCompleted(object arg) {
            if ((this.TimbrarRetencionXMLV2Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.TimbrarRetencionXMLV2Completed(this, new TimbrarRetencionXMLV2CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    public delegate void TimbrarRetencionXMLCompletedEventHandler(object sender, TimbrarRetencionXMLCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TimbrarRetencionXMLCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal TimbrarRetencionXMLCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    public delegate void TimbrarRetencionXMLV2CompletedEventHandler(object sender, TimbrarRetencionXMLV2CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TimbrarRetencionXMLV2CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal TimbrarRetencionXMLV2CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591